// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnyxjnvbdpawsrdwmsqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZueXhqbnZiZHBhd3NyZHdtc3FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMzMzNzUsImV4cCI6MjA3NzYwOTM3NX0.YWRbmR2VVnzs3czoB_FJnYLtKFMkzvGrX6bv4z9A71k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});